// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDlVbjUcHQJR74bBGEsA-NeWtHP-Q158U',
    appId: '1:938547180939:web:818b889871ed7e0f986b8e',
    messagingSenderId: '938547180939',
    projectId: 'social-media-5ef11',
    authDomain: 'social-media-5ef11.firebaseapp.com',
    storageBucket: 'social-media-5ef11.appspot.com',
    measurementId: 'G-YS485C9RMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABhfhGxKTVgHs12oyG0VLbiFMiJ0NzyR8',
    appId: '1:938547180939:android:2ce9326e8134067f986b8e',
    messagingSenderId: '938547180939',
    projectId: 'social-media-5ef11',
    storageBucket: 'social-media-5ef11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH-JmtBzV2i0bHJ1WZUhc_aCIJ-H71-50',
    appId: '1:938547180939:ios:0c45f1fb608c245a986b8e',
    messagingSenderId: '938547180939',
    projectId: 'social-media-5ef11',
    storageBucket: 'social-media-5ef11.appspot.com',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH-JmtBzV2i0bHJ1WZUhc_aCIJ-H71-50',
    appId: '1:938547180939:ios:2196aab8ed990dd4986b8e',
    messagingSenderId: '938547180939',
    projectId: 'social-media-5ef11',
    storageBucket: 'social-media-5ef11.appspot.com',
    iosBundleId: 'com.example.socialMedia.RunnerTests',
  );
}
